name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Build BrickPI
      run: |
          sudo apt-get install gcc-aarch64-linux-gnu
          make
      
